version: '3.3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=kodeprint
      - POSTGRES_PASSWORD=abc123/-
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=kodeprint@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
